### ISSUE TITLE
tests failed

### ISSUE THREAD

**Issue by anhanijr** [Uauy-Lab/bioruby-polyploid-tools#10]
Hi,
I posted the failed tests to Polymarker , and Alice suggested to post here, so...

Best wishes,

Antonio

[tests_fail.log](https://github.com/TGAC/bioruby-polyploid-tools/files/1435194/tests_fail.log)

**Comment by aliceminotto** [comment]
@homonecloco ?

**Comment by homonecloco** [comment]
I'm currently improving PolyMarker, I fixed this particular error already. But I'm in the middle of a medium size refactor.
