### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by anhanijr** [Uauy-Lab/bioruby-polyploid-tools#17]
I've installed new version and got following error...

Traceback (most recent call last):
	9: from /usr/local/bin/polymarker.rb:23:in `<main>'
	8: from /usr/local/bin/polymarker.rb:23:in `load'
	7: from /var/lib/gems/2.5.0/gems/bio-polyploid-tools-0.9.9/bin/polymarker.rb:11:in `<top (required)>'
	6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	4: from /var/lib/gems/2.5.0/gems/bio-polyploid-tools-0.9.9/lib/bioruby-polyploid-tools.rb:16:in `<top (required)>'
	3: from /var/lib/gems/2.5.0/gems/bio-polyploid-tools-0.9.9/lib/bioruby-polyploid-tools.rb:16:in `each'
	2: from /var/lib/gems/2.5.0/gems/bio-polyploid-tools-0.9.9/lib/bioruby-polyploid-tools.rb:18:in `block in <top (required)>'
	1: from /var/lib/gems/2.5.0/gems/bio-polyploid-tools-0.9.9/lib/bioruby-polyploid-tools.rb:18:in `require_relative'
/var/lib/gems/2.5.0/gems/bio-polyploid-tools-0.9.9/lib/bio/PolyploidTools/Mask.rb:11:in `<top (required)>': uninitialized constant Bio::PolyploidTools (NameError)

Best wishes

**Comment by homonecloco** [comment]
Hi, 
Sorry I haven't looked at this before, I was on leave and I'm just catching up with everything. 
Which OS and how did you install Ruby? I test using RVM for the gem management, but I may need to fix the order of the headers in order to fix it. If you give me more details of your installation I can try to reproduce it. 

@billyfish seems to be having the same issue, so I could probably use his setup to figure out which is the header I need to fix. 

Thanks, 
Ricardo.

**Comment by billyfish** [comment]
Hi chaps

You're more than  welcome to investigate our set up. I'm using Ubuntu 16,04 and 18.04, both with the same issue.

ubuntu 16:
ubuntu@grassroots-indexer:~/Projects/grassroots/services/polymarker-service/build/linux$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]


ubuntu 18:
billy@billy-Jo-PC:~/Applications/grassroots/apache$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]


if this helps

cheers

billy

**Comment by anhanijr** [comment]
Hi Ricardo, 


Thanks for contact me. 


I'ḿ using linux ubuntu 18.04 64 bits, installed ruby via apt. 
I solved the problem installing ruby-dev ( ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]) and an older version (0.7.3) of bio-polyploid-tools. 
It works fine, despite losing features of newer versions. 



Cheers, 


Antonio 
----- Mensagem original -----

De: "Ricardo H. Ramírez-Gonzalez" <notifications@github.com> 
Para: "homonecloco/bioruby-polyploid-tools" <bioruby-polyploid-tools@noreply.github.com> 
Cc: "Antonio Nhani Jr" <antonio.nhani@embrapa.br>, "Author" <author@noreply.github.com> 
Enviadas: Quarta-feira, 23 de janeiro de 2019 13:38:12 
Assunto: Re: [homonecloco/bioruby-polyploid-tools] typo? (#17) 


Hi, 
Sorry I haven't looked at this before, I was on leave and I'm just catching up with everything. 
Which OS and how did you install Ruby? I test using RVM for the gem management, but I may need to fix the order of the headers in order to fix it. If you give me more details of your installation I can try to reproduce it. 
@billyfish seems to be having the same issue, so I could probably use his setup to figure out which is the header I need to fix. 
Thanks, 
Ricardo. 
— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 


-- 



-- 
Antonio Nhani Jr. 
Pesquisador - Bioinformática 

Laboratório de Bioinformática Aplicada - LBA 

Embrapa Informática Agropecuária 

Empresa Brasileira de Pesquisa Agropecuária 

Campinas/SP 


antonio.nhani@embrapa.br 
Fone: (19) 3211-5700 ramal 5891 - Fax: (19) 3211-5754 

Av. André Tosello, 209 - Cidade Universitária, Campinas - SP 
CEP 13.083-886 
http://www.lmb.cnptia.embrapa.br/ 



____________________________________________________________________________
Aviso de confidencialidade

Esta mensagem da Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa), empresa publica federal  regida pelo disposto  na Lei Federal no. 5.851,  de 7 de dezembro de 1972,  e  enviada exclusivamente  a seu destinatario e pode conter informacoes  confidenciais, protegidas  por sigilo profissional.  Sua utilizacao desautorizada  e ilegal e  sujeita o infrator as penas da lei. Se voce  a recebeu indevidamente, queira, por gentileza, reenvia-la ao emitente, esclarecendo o equivoco.

Confidentiality note

This message from Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa), a government company  established under  Brazilian law (5.851/72), is directed exclusively to  its addressee  and may contain confidential data,  protected under  professional secrecy  rules. Its unauthorized  use is illegal and  may subject the transgressor to the law's penalties. If you are not the addressee, please send it back, elucidating the failure.

**Comment by homonecloco** [comment]
Thanks both to the heads up! So, seems like a problem with the OS ruby on Ubuntu systems. I have a machine at home I can use to try this. 
@anhanijr Once I find a fix, I would suggest to upgrade to the newer version, as changing blast instead of exonerate makes a big difference in the running time. 
Best,
Ricardo.

**Comment by anhanijr** [comment]
Thanks Ricardo! 


Best, 


Antonio 

----- Mensagem original -----

De: "Ricardo H. Ramírez-Gonzalez" <notifications@github.com> 
Para: "homonecloco/bioruby-polyploid-tools" <bioruby-polyploid-tools@noreply.github.com> 
Cc: "Antonio Nhani Jr" <antonio.nhani@embrapa.br>, "Mention" <mention@noreply.github.com> 
Enviadas: Quarta-feira, 23 de janeiro de 2019 14:09:41 
Assunto: Re: [homonecloco/bioruby-polyploid-tools] typo? (#17) 


Thanks both to the heads up! So, seems like a problem with the OS ruby on Ubuntu systems. I have a machine at home I can use to try this. 
@anhanijr Once I find a fix, I would suggest to upgrade to the newer version, as changing blast instead of exonerate makes a big difference in the running time. 
Best, 
Ricardo. 
— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 


-- 



-- 
Antonio Nhani Jr. 
Pesquisador - Bioinformática 

Laboratório de Bioinformática Aplicada - LBA 

Embrapa Informática Agropecuária 

Empresa Brasileira de Pesquisa Agropecuária 

Campinas/SP 


antonio.nhani@embrapa.br 
Fone: (19) 3211-5700 ramal 5891 - Fax: (19) 3211-5754 

Av. André Tosello, 209 - Cidade Universitária, Campinas - SP 
CEP 13.083-886 
http://www.lmb.cnptia.embrapa.br/ 



____________________________________________________________________________
Aviso de confidencialidade

Esta mensagem da Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa), empresa publica federal  regida pelo disposto  na Lei Federal no. 5.851,  de 7 de dezembro de 1972,  e  enviada exclusivamente  a seu destinatario e pode conter informacoes  confidenciais, protegidas  por sigilo profissional.  Sua utilizacao desautorizada  e ilegal e  sujeita o infrator as penas da lei. Se voce  a recebeu indevidamente, queira, por gentileza, reenvia-la ao emitente, esclarecendo o equivoco.

Confidentiality note

This message from Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa), a government company  established under  Brazilian law (5.851/72), is directed exclusively to  its addressee  and may contain confidential data,  protected under  professional secrecy  rules. Its unauthorized  use is illegal and  may subject the transgressor to the law's penalties. If you are not the addressee, please send it back, elucidating the failure.

**Comment by anhanijr** [comment]
Hi Ricardo, 

Following your suggestion i tried several versions already with blast use enabled. 

For my system, version 0.8.3 is the newest functional. 

Above this, the 
"/usr/lib/ruby/gems/2.5.0/gems/bio-polyploid-tools-0.8.4/lib/bio/PolyploidTools/Mask.rb:11:in `<top (required)>': uninitialized constant Bio::PolyploidTools (NameError)" 


appears in all versions from 0.8.4 to 0.8.9, when i stopped testing. 


Hope this gives you some help. 


Best, 


Antonio 
----- Mensagem original -----

De: "Ricardo H. Ramírez-Gonzalez" <notifications@github.com> 
Para: "homonecloco/bioruby-polyploid-tools" <bioruby-polyploid-tools@noreply.github.com> 
Cc: "Antonio Nhani Jr" <antonio.nhani@embrapa.br>, "Mention" <mention@noreply.github.com> 
Enviadas: Quarta-feira, 23 de janeiro de 2019 14:09:41 
Assunto: Re: [homonecloco/bioruby-polyploid-tools] typo? (#17) 


Thanks both to the heads up! So, seems like a problem with the OS ruby on Ubuntu systems. I have a machine at home I can use to try this. 
@anhanijr Once I find a fix, I would suggest to upgrade to the newer version, as changing blast instead of exonerate makes a big difference in the running time. 
Best, 
Ricardo. 
— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 


-- 



-- 
Antonio Nhani Jr. 
Pesquisador - Bioinformática 

Laboratório de Bioinformática Aplicada - LBA 

Embrapa Informática Agropecuária 

Empresa Brasileira de Pesquisa Agropecuária 

Campinas/SP 


antonio.nhani@embrapa.br 
Fone: (19) 3211-5700 ramal 5891 - Fax: (19) 3211-5754 

Av. André Tosello, 209 - Cidade Universitária, Campinas - SP 
CEP 13.083-886 
http://www.lmb.cnptia.embrapa.br/ 



____________________________________________________________________________
Aviso de confidencialidade

Esta mensagem da Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa), empresa publica federal  regida pelo disposto  na Lei Federal no. 5.851,  de 7 de dezembro de 1972,  e  enviada exclusivamente  a seu destinatario e pode conter informacoes  confidenciais, protegidas  por sigilo profissional.  Sua utilizacao desautorizada  e ilegal e  sujeita o infrator as penas da lei. Se voce  a recebeu indevidamente, queira, por gentileza, reenvia-la ao emitente, esclarecendo o equivoco.

Confidentiality note

This message from Empresa  Brasileira de Pesquisa  Agropecuaria (Embrapa), a government company  established under  Brazilian law (5.851/72), is directed exclusively to  its addressee  and may contain confidential data,  protected under  professional secrecy  rules. Its unauthorized  use is illegal and  may subject the transgressor to the law's penalties. If you are not the addressee, please send it back, elucidating the failure.

**Comment by homonecloco** [comment]
This has been fixed, thanks to the help of @billyfish . The next release should work on ubuntu.

**Comment by anhanijr** [comment]
Thank you guys!
