### ISSUE TITLE
--extract_found_contigs option is broken

### ISSUE THREAD

**Issue by FredericBGA** [Uauy-Lab/bioruby-polyploid-tools#22]
If you try to set `--extract_found_contigs` option, Polymarker.rb will fail:
`/polymarker.rb:315:in `do_align': undefined local variable or method `contigs_f' for main:Object (NameError)`

so we maybe need to change: `contigs_f` to `$contigs_f` in order to make it a global variable.

or we need to test if `--extract_found_contigs` is set and then pass the `contigs_f` as argument to `do_align`.

I don't know Ruby, so let me know which is the best solution. I can create a PR if you want.

**Comment by homonecloco** [comment]
I was adding some integration tests, so I took the chance to have a look. Thanks for reporting this, I missed bringing the variable ```contigs_f``` when adding support for blast. I didn't try it, as this variable extracts the full chromosome sequence. It is useful when you have fragmented assemblies.
