### ISSUE TITLE
Primer3 preference File

### ISSUE THREAD

**Issue by thomasmaggen** [Uauy-Lab/bioruby-polyploid-tools#5]
Hi,
This is really a useful tool! However, I sometimes encounter the problem that primers could not be designed because no primers meet the criteria set by primer3. I notice there is an option to upload a primer3preference file, so i want to try this to use more relaxed parameters.... How should the preference file be formatted?
Many thanks,
Thomas.

**Comment by homonecloco** [comment]
Hi Thomas, 
Do you have experience using primer3 from the command line? PolyMarker takes the same input format as the command line version of primer3:

TAG=VALUE

The valid tags are documented here:
http://mcardle.wisc.edu/mprime/help/primer3/primer3_manual.htm#globalTags
The feature hasn't been tested extensively, so if you come across any errors, please let me know and I'll try to solve it. 
Best, 
Ricardo.

**Comment by homonecloco** [comment]
Hi Thomas, did you manage to run PolyMarker with the custom preference file?

**Comment by thomasmaggen** [comment]
Hi Ricardo,
I managed to write the file in the correct format, and polymarker accepts it.
However for my set of sequences it did not result in different primers, or primers to be designed on sequences that failed before.  It's unclear to me if this is because the parameters were still not relaxed enough, or because polymarker would not incorporate the custom paramters.  I only had a small set of sequences, so for now I did not look more deeply into the issue.

**Comment by homonecloco** [comment]
Hi, 
You can have a look on the primer3_input_temp file, that contains the parameters sent to primer 3. If your options are present there, polymarker forwarded them correctly. Likewise, you can see the full output from primer3 in the corresponding primer3_output_temp file. It contains he detailed reason of why each tested primer failed. let me know if this is of any help

Ricardo

**Comment by thomasmaggen** [comment]
The parameters are there! Thank you very much for your support.
