### ISSUE TITLE
Error with gem install

### ISSUE THREAD

**Issue by ehsueh** [Uauy-Lab/bioruby-polyploid-tools#7]
Hi, I am getting the following error when I run `gem install bio-polyploid-tools` :
```
bam_tview_curses.c:41:20: fatal error: curses.h: No such file or directory
compilation terminated.
Makefile:129: recipe for target 'bam_tview_curses.o' failed
make: *** [bam_tview_curses.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/var/lib/gems/2.3.0/gems/bio-samtools-2.5.1/ext/Rakefile:28:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/bio-samtools-2.5.1/ext/Rakefile:27:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<main>'
Tasks: TOP => default => compile
(See full trace by running task with --trace) 
```
I already have Samtools on my machine, so why does gem need to reinstall it again? I am using ruby 2.3.1 and gem 2.6.10 on Ubuntu 16.04. I also have all the required tools (MAFFT, exonerate and Pimer3 installed through conda). Do you know how I can get PolyMarker to work? Thank you for your help.

**Comment by homonecloco** [comment]
Hi,
Cab you try to do this:

'''
Sudo apt get ncurses
'''

Best


Ricardo H. Ramirez G.

On 17 Feb 2017, at 23:18, ehsueh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I am getting the following error when I run gem install bio-polyploid-tools :

bam_tview_curses.c:41:20: fatal error: curses.h: No such file or directory
compilation terminated.
Makefile:129: recipe for target 'bam_tview_curses.o' failed
make: *** [bam_tview_curses.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/var/lib/gems/2.3.0/gems/bio-samtools-2.5.1/ext/Rakefile:28:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/bio-samtools-2.5.1/ext/Rakefile:27:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<main>'
Tasks: TOP => default => compile
(See full trace by running task with --trace)


I already have Samtools on my machine, so why does gem need to reinstall it again? I am using ruby 2.3.1 and gem 2.6.10 on Ubuntu 16.04. I also have all the required tools (MAFFT, exonerate and Pimer3 installed through conda). Do you know how I can get PolyMarker to work? Thank you for your help.

**Comment by ehsueh** [comment]
Thank you! That fixed it!
```
 sudo apt-get install libncurses5-dev libncursesw5-dev
```
