### ISSUE TITLE
Using --snp_list option

### ISSUE THREAD

**Issue by ehsueh** [Uauy-Lab/bioruby-polyploid-tools#9]
Hi Ricardo,
What is the difference between running PolyMarker by providing a snp list versus a marker list?
Also, what is the format of the snp list file if I want to use the --snp_list option? 
The [Ruby Doc](http://www.rubydoc.info/gems/bio-polyploid-tools/Bio%2FPolyploidTools%2FSNP%2Eparse) has some hints. But I'm still not quite sure what the columns are from the variable names. Do you have an example file somewhere? 
Thanks you.

**Comment by homonecloco** [comment]
Hi,
I'm sorry for not getting back to you earlier, I just added the documentation in the main page of this options:
https://github.com/TGAC/bioruby-polyploid-tools/commit/4d9f6116c87e565a3231453fc9736be454d1cc47
I hope this is clear now? 
Best, 
Ricardo.

**Comment by ehsueh** [comment]
Thanks, Ricardo.
Following the format described 
> IWGSC_CSS_1AL_scaff_110,C,519,A,2A

I tried using a snp_list file with rows like:
> chr2A,C,736735202,A,2A

At first I was getting an error like
```
/var/lib/gems/2.3.0/gems/bioruby-polyploid-tools/bin/polymarker.rb:265:in `block (2 levels) in <main>': undefined method `rise' for main:Object (NoMethodError)
Did you mean?  raise
```
I'm not familiar with ruby but it seems we do want to raise exceptions there so I changed the codes in polymarker.rb to 

```
264     else
265       raise Bio::DB::Exonerate::ExonerateException.new "Wrong number of arguments. "
266     end
267     raise Bio::DB::Exonerate::ExonerateException.new "No SNP for line '#{line}'" if snp == nil
```
Then I received an error on argument as follow:
```
/var/lib/gems/2.3.0/gems/bioruby-polyploid-tools/bin/polymarker.rb:265:in `block (2 levels) in <main>': Wrong number of arguments.  (Bio::DB::Exonerate::ExonerateException)
	from /var/lib/gems/2.3.0/gems/bioruby-polyploid-tools/bin/polymarker.rb:241:in `each_line'
	from /var/lib/gems/2.3.0/gems/bioruby-polyploid-tools/bin/polymarker.rb:241:in `block in <main>'
	from /var/lib/gems/2.3.0/gems/bioruby-polyploid-tools/bin/polymarker.rb:240:in `open'
	from /var/lib/gems/2.3.0/gems/bioruby-polyploid-tools/bin/polymarker.rb:240:in `<main>'
```
Which went away when I specify `--reference` along with the `--contigs` option. :+1: 
Thanks again! :smile:
